kafka:
  bootstrap-server: localhost:9092
  group-id: aggregator-service
  topics:
    sensors: telemetry.sensors.v1
    snapshots: telemetry.snapshots.v1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 0